### ISSUE TITLE
Calculation of CI for I^2

### ISSUE THREAD

**Issue by wviechtb** [msrosenberg/MetaWin#20]
Something seems to be off with the way the CI for I^2 is calculated. These are the data from the first example in chapter 18 from Borenstein et al. (2009):

```
yi	vi
0.09452	0.03295
0.27736	0.03070
0.36654	0.04988
0.66438	0.01051
0.46181	0.04266
0.18516	0.02342
```

As shown in the book, the CI for I^2 is 0% to 83.12%. In contrast, MetaWin gives a CI with bounds 34.5676% to 73.4908%. As far as I can tell, the issue stems from [this part](https://github.com/msrosenberg/MetaWin/blob/2a16f7441ef0956d419d64465bb8aa2161e95a8d/src/MetaWinAnalysisFunctions.py#L377C20-L378). `se` is the SE of $\ln(H)$, but then you use it in the calculations as if it was the SE of $\ln(H^2)$. I think `lower_h2 = math.exp(ln_h2 - z*2*se)` would be correct (and analogously for `upper_h2`) since the SE of $\ln(H^2)$ is twice that of $\ln(H)$.

**Comment by msrosenberg** [comment]
Looks like you're correct. I went back to the source where I got the formulas from and it listed them as the SE of ln(H^2), which is how I programmed (and tested) it. I then went back to the original papers and they list the formula as the SE of ln(H).
