### ISSUE TITLE
Dont work in mac intel

### ISSUE THREAD

**Issue by obifran** [msrosenberg/MetaWin#7]
Hello

Thanks for your work. Now the programa for mac os not work in procesor intel. 

I would like to have a intel version.

If you need testing, i could you help.

Thanks

**Comment by msrosenberg** [comment]
That is disappointing. I'll see if I can get hold of an Intel-based Mac in order to produce a "pre-compiled" version for that system.

**Comment by LorMeBioAI** [comment]
I cannot see the page of software on my Macbook M1 pro of Monterey 12 when I opening the Metawin.

**Comment by msrosenberg** [comment]
I have now built a version of MetaWin on an Intel-based Mac and made this available on the website as a separate download. Please let me know if there are any issues with it.

**Comment by obifran** [comment]
First of all, thank you for the effort and work done to be able to use the application in an intel processor.

I summarize what I have done:
1. The download has worked correctly from the web page.
2. Opening the file.dmg file was successful.
3. Move metawin.app file to applications, it worked fine.
4. When you open the program, a window appears that warns you that to open applications from an unknown developer you have to go to preferences->security and allow them to open.

<img width="853" alt="Captura de Pantalla 2022-10-26 a las 21 14 55" src="https://user-images.githubusercontent.com/36841337/198117516-8d36b895-37ed-4d5e-9673-aaebf8a450f2.png">

In general it seems to work correctly, it just has a little delay to open. Similar behavior to what happens when opening in Windows 11.

[https://support.apple.com/es-es/guide/mac-help/mh40616/mac](url)

My configuration is:

<img width="373" alt="Captura de Pantalla 2022-10-26 a las 21 15 10" src="https://user-images.githubusercontent.com/36841337/198117593-74343543-5073-4a66-a450-f02aa8688aa1.png">

Thank so much. If you need more testing or video, tell me. 

Thank!!!!

**Comment by msrosenberg** [comment]
Great! The slowness when opened is due to the program being written in Python and having to go through an initial lengthy compilation every time it starts. It should run fairly quickly once it opens, but that initial wait can definitely be slow. Unfortunately, unlike in Windows, I don't currently have a way to show a splash screen while it's opening on the Mac to help indicate it's working on opening.

Let me know if there are other problems as you use it.
