### ISSUE TITLE
Cumulative Meta-Analysis

### ISSUE THREAD

**Issue by Zoolouis** [msrosenberg/MetaWin#9]
Hi. Congrats for this great software.
I am trying to run a cumulative analysis, but I always get the same result. It orders the studies by Effect size, not Year. I even tried changing Year by Order (simply 1, 2, 3, etc.), or changing the Years randomly, and always get the exact same results.
Any idea what might be going on?

**Comment by msrosenberg** [comment]
It might be a few days before I can look into this, but I'll let you know what I find and if I need more details.

**Comment by msrosenberg** [comment]
I've confirmed the bug. It used to work but I introduced an error when I refactored some of the code awhile back. Will be fixed soon.
